version: '3.4'
services:
  backend:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'testdb'
      POSTGRES_PASSWORD: '123'
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
