version: "3.4"
services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "testdb"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql